# Generated by Django 3.1.3 on 2020-11-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=500)),
                ('search_time', models.DateTimeField(verbose_name='search push time')),
            ],
        ),
    ]
